### ISSUE TITLE
Add Gitpod Support 

### ISSUE THREAD

**Issue by vkassingh** [tharun143/KwoC-EMS#10] opened 2020-12-16 12:16 UTC
Add Gitpod Support 
Local installations can be tedious. The contributors can save time by using gitpod

**Comment by vkassingh** [comment] 2020-12-16 12:17
I would like to work on this issue. please assign it to me

**Comment by tharun143** [comment] 2020-12-16 13:35
Sorry, It's not a bug and also please follow the rules to submit a bug. Explain to me briefly about it then I will assign it. As of now closing it

**Closed by tharun143** 2020-12-16 13:35 UTC
Labels: bug
